### ISSUE TITLE
retrieval tool

### ISSUE THREAD

**Issue by tony-lii** [dotref/paper-machine#10]
gain more experience for text based rag, be clear about what happens each step. 
* search agent -> able to return a/multiple reference text(s) relevant to the input prompt by user.

**Comment by beepo34** [comment]
- SentenceWindowNodeParser splits text documents into nodes each containing a sentence and the context around it
- VectorStoreIndex stores node embeddings in an index in memory for retrieval
- MetadataReplacementPostProcessor replaces node content with sentence window context to prepare for generation.
- index supports insertion and deletion of documents
