### ISSUE TITLE
Vector Database: Granularity - Build Index for Each Uploaded File

### ISSUE THREAD

**Issue by SaltedFishLZ** [dotref/paper-machine#24]
Do some research on the following options:
1. llama-index folder index tool
2. managing it by yourself (e.g., a pkl for FAISS of each file)

**Comment by beepo34** [comment]
- implemented using llama-index approach in [branch](https://github.com/dotref/paper-machine/tree/rag-skeleton)
- index creation/deletion/persistence works
- possible integration with mongodb/redis for index store
