### ISSUE TITLE
Web Frontend: Display the Primary Source

### ISSUE THREAD

**Issue by SaltedFishLZ** [dotref/paper-machine#25]
RAG Team:
provide the information

Randy: 
- [ ] Jump to a certain file
- [ ] Jump to a certain page (for PDF)

**Comment by SaltedFishLZ** [comment]
Hi, the RAG team (@wayneshix @beepo34 @tony-lii ), please decide on who will be PRIMARILY responsible for the interaction with Randy.

**Comment by tony-lii** [comment]
I have a due from the nlp class, not sure how long it's gonna take to finish as it's pretty huge
