### ISSUE TITLE
Data Collection and Engineering

### ISSUE THREAD

**Issue by beepo34** [dotref/paper-machine#29]
Find sample files for the purpose of the agents course project demo.
Files should contain detailed information about specific car models/car repair procedures for the purpose of generating detailed instructions for car repairs. Example interaction [here](https://github.com/dotref/paper-machine/blob/cbb3fddd26ec8aea22bf5f2c7e90b336a7e5c92f/backend/autogen.ipynb)

**Comment by vnach** [comment]
files should be in "assets" folder in main branch

Consists of 2 pdf vehicle manuals and a "Peugeot J5 Manual Items" Folder with individual pdfs for "Breaks", "Clutch", etc.
